version: "3"
services:
  onair:
    build:
      context: ./
      dockerfile: .docker/dev.Dockerfile
    container_name: onair
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
    depends_on:
      - cachedb
  cachedb:
    image: redis:latest
    container_name: cachedb
    hostname: cachedb
